//! Chessboard data model for the Slint interface.
//!
//! Provides the 64 squares ([`SquareData`]) expected by the
//! `ChessBoard` component in `board.slint`. The [`SquareData`] and
//! [`ChessBoard`] types are generated by `slint::include_modules!()` from
//! `ui/app.slint`.
//!
//! # Coordinate convention
//!
//! | Field | 0                  | 7                 |
//! |-------|--------------------|-------------------|
//! | `row` | rank 8 (top)       | rank 1 (bottom)   |
//! | `col` | file a (left)      | file h (right)    |
//!
//! This convention places the black pieces at the top (rows 0-1) and the
//! white pieces at the bottom (rows 6-7), as seen from the white
//! player's side — standard for a chess GUI.
//!
//! # Square color
//!
//! `is_light = (row + col) % 2 == 0`
//!
//! Verification: a1 (row=7, col=0) → (7+0)%2=1 → `false` = dark square ✓
//!               h1 (row=7, col=7) → (7+7)%2=0 → `true`  = light square ✓
//!               a8 (row=0, col=0) → (0+0)%2=0 → `true`  = light square ✓

use crate::SquareData;

// ── Initial position ─────────────────────────────────────────────────────────
//
// 8×8 table: each entry = (svg_identifier, side).
//   side 0 = empty square (identifier "")
//   side 1 = white piece
//   side 2 = black piece
//
// SVG identifiers: 2 ASCII characters — first 'w'/'b', second 'K'/'Q'/'R'/'B'/'N'/'P'.
// Correspond to the file names in assets/pieces/<id>.svg.
//
// Line 0 = rank 8, line 7 = rank 1.
// Column 0 = file a, column 7 = file h.
#[rustfmt::skip]
const INITIAL: [[(&str, i32); 8]; 8] = [
    // rank 8 — black pieces
    [("bR",2), ("bN",2), ("bB",2), ("bQ",2), ("bK",2), ("bB",2), ("bN",2), ("bR",2)],
    // rank 7 — black pawns
    [("bP",2), ("bP",2), ("bP",2), ("bP",2), ("bP",2), ("bP",2), ("bP",2), ("bP",2)],
    // ranks 6-3 — empty squares
    [("",0),   ("",0),   ("",0),   ("",0),   ("",0),   ("",0),   ("",0),   ("",0)],
    [("",0),   ("",0),   ("",0),   ("",0),   ("",0),   ("",0),   ("",0),   ("",0)],
    [("",0),   ("",0),   ("",0),   ("",0),   ("",0),   ("",0),   ("",0),   ("",0)],
    [("",0),   ("",0),   ("",0),   ("",0),   ("",0),   ("",0),   ("",0),   ("",0)],
    // rank 2 — white pawns
    [("wP",1), ("wP",1), ("wP",1), ("wP",1), ("wP",1), ("wP",1), ("wP",1), ("wP",1)],
    // rank 1 — white pieces
    [("wR",1), ("wN",1), ("wB",1), ("wQ",1), ("wK",1), ("wB",1), ("wN",1), ("wR",1)],
];

// ── Public API ───────────────────────────────────────────────────────────────

/// Generates the 64 [`SquareData`] of the initial position.
///
/// The vector is in row-by-row scan order (row 0..7, col
/// 0..7), which is the natural order for a [`slint::VecModel`].
// Clippy: `#[allow(cast_sign_loss)]` — `row`/`col` come from `0..8_i32`,
// never negative; conversion safe by construction.
#[must_use]
#[allow(clippy::cast_sign_loss)]
pub fn initial_squares() -> Vec<SquareData> {
    let mut squares = Vec::with_capacity(64);
    for row in 0..8_i32 {
        for col in 0..8_i32 {
            let (piece_char, piece_side) = INITIAL[row as usize][col as usize];
            squares.push(SquareData {
                row,
                col,
                piece_char: piece_char.into(),
                is_light: (row + col) % 2 == 0,
                piece_side,
                // Phase 6.5 fields — inactive at the initial position
                is_selected:     false,
                is_legal_target: false,
                is_last_from:    false,
                is_last_to:      false,
                // PHASE 67 — initial position: no king is ever in check.
                is_king_in_check: false,
                // PHASE 68 — no piece selected at the initial position:
                // no assistance badge to compute.
                is_capture_risk: false,
                is_gives_check:  false,
                is_gives_mate:   false,
                // PHASE 69 — initial position: no king is ever mated.
                is_mated_king: false,
            });
        }
    }
    squares
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Basic structure ───────────────────────────────────────────────────────

    #[test]
    fn test_count_64_squares() {
        assert_eq!(initial_squares().len(), 64, "l'échiquier doit avoir 64 cases");
    }

    #[test]
    fn test_32_pieces_on_board() {
        let count = initial_squares().iter().filter(|s| s.piece_side != 0).count();
        assert_eq!(count, 32, "32 pièces au total en position initiale");
    }

    #[test]
    fn test_16_white_16_black_pieces() {
        let sq = initial_squares();
        let white = sq.iter().filter(|s| s.piece_side == 1).count();
        let black = sq.iter().filter(|s| s.piece_side == 2).count();
        assert_eq!(white, 16, "16 pièces blanches");
        assert_eq!(black, 16, "16 pièces noires");
    }

    // ── Specific pieces ────────────────────────────────────────────────────

    #[test]
    fn test_e1_is_white_king() {
        // e1 = file e (col 4), rank 1 (row 7)
        let sq = initial_squares().into_iter().find(|s| s.row == 7 && s.col == 4).unwrap();
        assert_eq!(sq.piece_char.as_str(), "wK", "e1 = roi blanc");
        assert_eq!(sq.piece_side, 1);
    }

    #[test]
    fn test_e8_is_black_king() {
        // e8 = file e (col 4), rank 8 (row 0)
        let sq = initial_squares().into_iter().find(|s| s.row == 0 && s.col == 4).unwrap();
        assert_eq!(sq.piece_char.as_str(), "bK", "e8 = roi noir");
        assert_eq!(sq.piece_side, 2);
    }

    #[test]
    fn test_center_is_empty() {
        // Ranks 3-6 (rows 2-5) must be entirely empty
        let sq = initial_squares();
        let center: Vec<_> = sq.iter().filter(|s| s.row >= 2 && s.row <= 5).collect();
        assert_eq!(center.len(), 32, "32 cases centrales");
        for s in center {
            assert_eq!(s.piece_char.as_str(), "", "case centrale vide row={} col={}", s.row, s.col);
            assert_eq!(s.piece_side, 0);
        }
    }

    // ── Color alternation ─────────────────────────────────────────────────

    #[test]
    fn test_a1_is_dark() {
        // a1 = col 0, row 7 → (7+0)%2=1 → dark square
        let sq = initial_squares().into_iter().find(|s| s.row == 7 && s.col == 0).unwrap();
        assert!(!sq.is_light, "a1 doit être une case noire");
    }

    #[test]
    fn test_h1_is_light() {
        // h1 = col 7, row 7 → (7+7)%2=0 → light square
        let sq = initial_squares().into_iter().find(|s| s.row == 7 && s.col == 7).unwrap();
        assert!(sq.is_light, "h1 doit être une case blanche");
    }

    #[test]
    fn test_adjacent_squares_alternate() {
        // All horizontally adjacent squares must alternate
        let squares = initial_squares();
        for row in 0..8_i32 {
            for col in 0..7_i32 {
                let s1 = squares.iter().find(|s| s.row == row && s.col == col).unwrap();
                let s2 = squares.iter().find(|s| s.row == row && s.col == col + 1).unwrap();
                assert_ne!(
                    s1.is_light, s2.is_light,
                    "les cases adjacentes doivent alterner (row={row}, col={col})"
                );
            }
        }
    }
}
