//! Crate `gui` — Vendetta Chess graphical interface.
//!
//! Built on top of [Slint](https://slint.dev). The window's entry point
//! is [`AppWindow`]; translations are handled via the Slint global [`Tr`]
//! fed by [`i18n_bridge::apply_translations`].
//!
//! # Typical startup (Phase 6.3+)
//!
//! ```no_run
//! use gui::{AppWindow, Tr, i18n_bridge};
//! use i18n::Lang;
//! use slint::ComponentHandle as _;
//!
//! let lang = Lang::Fr;
//! i18n::init(lang);
//! let window = AppWindow::new().unwrap();
//! i18n_bridge::apply_translations(&window.global::<Tr>(), lang);
//! window.set_status_text(i18n::translate("board.turn.white").into());
//! window.set_is_white_turn(true);
//! window.run().unwrap();
//! ```

// Types generated by slint-build from `ui/app.slint`.
// Exports: AppWindow, Tr, SquareData (and any type exported in the .slint file).
slint::include_modules!();

/// Runs `body` (the work performed inside a fire-and-forget
/// `std::thread::spawn` background thread — a long import, engine
/// analysis, or hint computation) wrapped in
/// [`std::panic::catch_unwind`].
///
/// None of these background threads (import/analysis/hint threads in
/// `main.rs`, [`analysis_bridge::AnalysisBridge::start`]) store a
/// `JoinHandle` (deliberate choice: nothing needs to await them),
/// which means that if `body` panics instead of returning normally,
/// it never reaches its own `slint::invoke_from_event_loop` cleanup at
/// the end — any `..._active`/`..._computing`/`engine_thinking` guard
/// flag `body` was responsible for resetting then stays stuck forever
/// (until a full application restart), permanently disabling the
/// corresponding button/control with no error ever shown to the user.
/// See `Analyse_Projet/AUDIT_ROBUSTESSE_2026-07-11.md`, finding 1.2.
///
/// `on_panic` runs on the UI thread (via `invoke_from_event_loop`,
/// like every other UI mutation) and is responsible for resetting
/// whichever state `body` would otherwise have left stuck, plus
/// informing the user if relevant. It is a plain `fn` (not a closure)
/// since none of the current call sites need to capture anything
/// beyond the `&AppWindow` they receive — this keeps every call site
/// trivially `Send`.
pub fn run_guarded_thread<F>(body: F, window: slint::Weak<AppWindow>, on_panic: fn(&AppWindow))
where
    F: FnOnce() + std::panic::UnwindSafe,
{
    if std::panic::catch_unwind(body).is_err() {
        let _ = slint::invoke_from_event_loop(move || {
            if let Some(w) = window.upgrade() {
                on_panic(&w);
            }
        });
    }
}

pub mod analysis_bridge;
pub mod board_model;
pub mod chess_clock;
pub mod debug_log;
pub mod engine_scan;
pub mod game_bridge;
pub mod game_controller;
pub mod i18n_bridge;
pub mod pdf_export;
pub mod png_export;
pub mod prefs;
pub mod puzzle_session;
pub mod tournament_runner;
