//! Error types for the SCID decoder.
//!
//! Two levels, by design:
//! - [`ScidError`]: error at the FILE level (invalid magic, unsupported
//!   version, I/O). Fatal: the entire database cannot be opened.
//! - [`GameDecodeError`]: error at the level of A SINGLE GAME (unknown
//!   encoding, non-standard starting position, variation encountered in V1,
//!   illegal move once resolved by `chess_core`...). Not fatal: the
//!   game is counted as "skipped" by the caller
//!   (`crates/db`), import of the rest of the database continues.

use std::fmt;
use std::io;

/// Fatal error: the database (the file triplet) cannot be opened.
#[derive(Debug)]
pub enum ScidError {
    /// Read/open error on one of the three files.
    Io(io::Error),
    /// The magic number at the start of the file does not match the expected format.
    BadMagic,
    /// Unsupported version number (si4: only version 400 is
    /// currently written/read by the reference implementation).
    BadVersion(u16),
    /// File truncated or of a size inconsistent with the expected format.
    Truncated(&'static str),
}

impl fmt::Display for ScidError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io(e)           => write!(f, "erreur de lecture : {e}"),
            Self::BadMagic        => write!(f, "nombre magique invalide (fichier non SCID ?)"),
            Self::BadVersion(v)   => write!(f, "version de format non supportée : {v}"),
            Self::Truncated(what) => write!(f, "fichier tronqué ou corrompu : {what}"),
        }
    }
}

impl std::error::Error for ScidError {}

impl From<io::Error> for ScidError {
    fn from(e: io::Error) -> Self {
        Self::Io(e)
    }
}

/// Non-fatal error: a single game could not be decoded.
///
/// The `SCID_VERSION` base documented here is deliberately terse toward the
/// end user (it is counted in `ImportSummary::skipped` by
/// `crates/db`, not displayed game by game); the detail is for diagnostics.
#[derive(Debug)]
pub enum GameDecodeError {
    /// The game has a non-standard starting position (START flag or custom
    /// FEN). Not supported in V1 (see `SUIVI_PLAN_ACTION.md`, V1 scope).
    NonStandardStart,
    /// The game contains at least one variation (sub-line). Not supported in
    /// V1: only the main line is imported.
    ContainsVariations,
    /// The game contains a null move ("null move"), which has no equivalent
    /// in `chess_core`.
    NullMove,
    /// A byte of the move stream does not match any known control token
    /// nor a decodable move (corrupted stream or unrecognized format).
    BadMoveStream(&'static str),
    /// The decoded move (origin/destination/promotion) does not match any
    /// legal move generated by `chess_core` in the current position — a
    /// sign either of file corruption or of a decoding bug to fix.
    IllegalMove { ply: usize },
    /// The game blob in the `.sg4`/`.sg5` has a length inconsistent
    /// with what the `IndexEntry` indicates (offset/length out of the file's bounds).
    BadOffset,
}

impl fmt::Display for GameDecodeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NonStandardStart      => write!(f, "position de départ non standard (non supporté en V1)"),
            Self::ContainsVariations    => write!(f, "partie avec variantes (non supporté en V1)"),
            Self::NullMove              => write!(f, "coup nul rencontré (non représentable)"),
            Self::BadMoveStream(what)   => write!(f, "flux de coups corrompu : {what}"),
            Self::IllegalMove { ply }   => write!(f, "coup illégal au demi-coup {ply}"),
            Self::BadOffset             => write!(f, "offset/longueur de partie hors bornes du fichier .sg"),
        }
    }
}

impl std::error::Error for GameDecodeError {}
